package pet.store.utils;

import io.restassured.http.ContentType;
import io.restassured.response.ValidatableResponse;

import java.util.Map;

import static io.restassured.RestAssured.baseURI;
import static io.restassured.RestAssured.given;
import static pet.store.utils.JsonProcessor.*;
import static pet.store.utils.ResourcesConnections.env;
import static pet.store.utils.ResourcesConnections.temp;


public class SendRequest {
    static {
        baseURI = env.getProperty("baseUrl");
    }
    public static ValidatableResponse sendRequest(String httpMethod, String endpoint, String param) throws Exception {
        ValidatableResponse response = null;
        switch (httpMethod.toUpperCase()) {
            case "POST":
                response = given().contentType(ContentType.JSON).body(param).when().post(endpoint).then().log().body();
                break;
            case "GET":
                response = given().when().get(endpoint).then().log().body();
                break;
            case "PUT":
                response = given().contentType(ContentType.JSON).body(param).when().put(endpoint).then().log().body();
                break;
            case "DELETE":
                response = given().when().delete(endpoint).then().log().body();
                break;
            default:
                throw new Exception("method: " + httpMethod + " isn't supported.");
        }
        return response;
    }

    public static ValidatableResponse sendRequest2(Map<String, String> requestSettings) {
        ValidatableResponse response = null;
        String endpoint = requestSettings.get("endpoint");
        String urlParam = requestSettings.get("urlParam");
        String method = requestSettings.get("method");
        String contentType = requestSettings.get("contendType");
        String requestBody = requestSettings.get("requestBody");
        String fieldsToAutoGenerate = requestSettings.get("fieldsToAutoGenerate");
        String fieldsGetFromResponse = requestSettings.get("fieldsGetFromResponse");
        String urlParamGetFromResponse = requestSettings.get("urlParamGetFromResponse");

        // Process endpoint
        if (!"none".equalsIgnoreCase(urlParam)) {
            if ("none".equalsIgnoreCase(urlParamGetFromResponse)) {
                endpoint += urlParam;
            } else {
                String[] keys = urlParamGetFromResponse.split(",");
                for (int i = 0; i < keys.length; i++) {
                    urlParam = urlParam.replaceFirst("\\?", temp.get(keys[i]));
                }
                endpoint += urlParam;
            }
        }
        // Process requestBody
        if (!"none".equalsIgnoreCase(requestBody)) {
            if (requestBody.contains(".json")) {
                    requestBody = getRequestBodyWithDataFromResponse(getRequestBodyWithAutoGeneratedData(getJSONObject(requestBody), fieldsToAutoGenerate), fieldsGetFromResponse).toString();
            } else {
                //TODO replace specific fields with the value of fieldsToAutoGenerate and fieldsGetFromResponse (eg. {"id": ?, "name", ?}
            }
        }


        switch (method.toUpperCase()) {
            case "POST":
                response = given().contentType(contentType).body(requestBody).when().post(endpoint).then().log().body();
                break;
            case "GET":
                response = given().when().get(endpoint).then().log().body();
                break;
            case "PUT":
                response = given().contentType(contentType).body(requestBody).when().put(endpoint).then().log().body();
                break;
            case "DELETE":
                response = given().when().delete(endpoint).then().log().body();
                break;
            default:
                System.out.println(("method: " + method + " isn't supported."));
        }
        return response;
    }

    public static void main(String[] args) {
//        String fileName = "update_a_pet.json";
//        String method =
//        FileReader fr = null;
//        try {
//            fr = new FileReader(filePath);
//            JSONObject jsonObject = (JSONObject) new JSONParser().parse(fr);
//            int code = given().contentType("application/x-www-form-urlencoded").body(jsonObject.toString()).when().post("https://petstore.swagger.io/v2" + "/pet/3").then().log().everything().extract().statusCode();
////            int code = given().body(jsonObject.toString()).when().post("https://petstore.swagger.io/v2" + "/pet/1").then().log().body().extract().statusCode();
//            System.out.println(code);
//        } catch (IOException | ParseException e) {
//            throw new RuntimeException(e);
//        } finally {
//            if (fr != null) {
//                try {
//                    fr.close();
//                } catch (IOException e) {
//                    throw new RuntimeException(e);
//                }
//            }
//        }
    }
}
